package com.example.solarsystem.model

enum class AppLanguage(val code: String, val displayName: String) {
    EN("en", "English"),
    GU("gu", "ગુજરાતી (Gujarati)"),
    HI("hi", "हिंदी (Hindi)"),
    ES("es", "Español"),
    FR("fr", "Français"),
    JA("ja", "日本語 (Japanese)")
}

data class LocalizedStrings(
    val title: String,
    val play: String,
    val pause: String,
    val today: String,
    val reset: String,
    val aboutApp: String,
    val helpBtn: String,
    val helpTitle: String,
    val searchGoogle: String,
    val galSliderText: String,
    val focusTargetLabel: String,
    val freeCam: String,
    val visibility: String,
    val toggleAll: String,
    val planetLabels: String,
    val moonLabels: String,
    val starLabels: String,
    val constellationLines: String,
    val galaxyView: String,
    val cometOort: String,
    val asteroidBelt: String,
    val solarPaths: String,
    val helicalPaths: String,
    val galOrbit: String,
    val helpItems: List<String>,
    val developerName: String,
    val developerPhone: String,
    val developerEmail: String,
    val developerInstagram: String,
    val feedbackPrompt: String,
    val names: Map<String, String>,
    val moonNames: Map<String, List<String>>
)

object Localization {
    private val en = LocalizedStrings(
        title = "Helical Solar System by Raj Baria",
        play = "Play",
        pause = "Pause",
        today = "Today",
        reset = "Reset Camera",
        aboutApp = "About App",
        helpBtn = "Help & Guide",
        helpTitle = "How to Use",
        searchGoogle = "Ask on Google",
        galSliderText = "Galaxy 360°:",
        focusTargetLabel = "Focus Camera On:",
        freeCam = "Free Camera",
        visibility = "Visibility:",
        toggleAll = "Toggle All",
        planetLabels = "Planets: ",
        moonLabels = "Moons: ",
        starLabels = "Nearby Stars: ",
        constellationLines = "Constellations: ",
        galaxyView = "Galaxy: ",
        cometOort = "Comets & Oort: ",
        asteroidBelt = "Asteroid Belt: ",
        solarPaths = "Solar Orbits: ",
        helicalPaths = "Helical Paths: ",
        galOrbit = "Galactic Orbit: ",
        helpItems = listOf(
            "Perfect Keplerian Math: 100% accurate NASA JPL J2000 orbital parameters.",
            "Asteroid Alert: Track near-Earth objects like the famous Apophis (99942).",
            "Retrograde Physics: Venus, Uranus and Triton correctly orbit or spin backwards.",
            "Helical Vortex: As the Sun travels around Sagittarius A*, planets trace 3D helical spirals through space.",
            "Gestures: One finger drag to rotate view, two fingers to pan, pinch to zoom."
        ),
        developerName = "Rajkumar Baria",
        developerPhone = "+91 6352840795",
        developerEmail = "rk3171998@gmail.com",
        developerInstagram = "@rajsbaria",
        feedbackPrompt = "Your valuable feedback is warmly welcomed!",
        names = mapOf(
            "sun" to "Sun", "mercury" to "Mercury", "venus" to "Venus", "earth" to "Earth",
            "mars" to "Mars", "ceres" to "Ceres", "jupiter" to "Jupiter", "saturn" to "Saturn",
            "uranus" to "Uranus", "neptune" to "Neptune", "pluto" to "Pluto", "haumea" to "Haumea",
            "makemake" to "Makemake", "eris" to "Eris", "halley" to "Halley's Comet",
            "apophis" to "Apophis (NEO)", "asteroidBelt" to "Asteroid Belt", "galCenter" to "Sagittarius A*",
            "proximaCentauri" to "Proxima Centauri (4.24 LY)", "alphaCentauri" to "Alpha Centauri A&B (4.37 LY)",
            "barnardsStar" to "Barnard's Star (5.96 LY)", "sirius" to "Sirius (8.6 LY)",
            "centaurus" to "Centaurus", "ursaMajor" to "Ursa Major", "orion" to "Orion",
            "canisMajor" to "Canis Major", "scorpius" to "Scorpius", "sagittarius" to "Sagittarius"
        ),
        moonNames = mapOf(
            "earth" to listOf("Moon"),
            "mars" to listOf("Phobos", "Deimos"),
            "jupiter" to listOf("Io", "Europa", "Ganymede", "Callisto"),
            "saturn" to listOf("Titan", "Enceladus", "Mimas"),
            "uranus" to listOf("Titania", "Oberon"),
            "neptune" to listOf("Triton"),
            "pluto" to listOf("Charon", "Styx", "Nix", "Kerberos", "Hydra"),
            "haumea" to listOf("Hiʻiaka", "Namaka"),
            "makemake" to listOf("MK2"),
            "eris" to listOf("Dysnomia")
        )
    )

    private val gu = LocalizedStrings(
        title = "હેલિકલ સૌરમંડળ (રાજ બારીઆ)",
        play = "ચલાવો",
        pause = "રોકો",
        today = "આજે",
        reset = "રીસેટ કેમેરા",
        aboutApp = "એપ વિશે",
        helpBtn = "હેલ્પ / માર્ગદર્શિકા",
        helpTitle = "એપ્લિકેશનનો ઉપયોગ",
        searchGoogle = "ગૂગલ પર વધુ શોધો",
        galSliderText = "ગેલેક્સી ૩૬૦°:",
        focusTargetLabel = "કેમેરા ફોકસ:",
        freeCam = "ફ્રી કેમેરા",
        visibility = "માર્ગ પસંદગી:",
        toggleAll = "બધા",
        planetLabels = "ગ્રહો: ",
        moonLabels = "ઉપગ્રહો: ",
        starLabels = "નજીકના તારા: ",
        constellationLines = "તારામંડળ રેખાઓ: ",
        galaxyView = "ગેલેક્સી: ",
        cometOort = "ધૂમકેતુ અને ઊર્ટ વાદળ: ",
        asteroidBelt = "એસ્ટેરોઇડ બેલ્ટ: ",
        solarPaths = "સૌર કક્ષા: ",
        helicalPaths = "કુંડલાકાર માર્ગ: ",
        galOrbit = "ગેલેક્ટિક કક્ષા: ",
        helpItems = listOf(
            "Scientifically Accurate: NASA JPL J2000 ડેટા દ્વારા 100% સચોટ ગતિ અને કક્ષાઓ!",
            "Asteroid Alert: પૃથ્વીની નજીક આવતા 'એપોફિસ' (Apophis) એસ્ટેરોઇડ ને જુઓ.",
            "Retrograde Physics: શુક્ર અને યુરેનસ ઉલ્ટી દિશામાં ભ્રમણ કરે છે.",
            "ગેલેક્ટીક મોશન: સૂર્ય આકાશગંગામાં આગળ વધતાં ગ્રહો હેલિકલ (કુંડલાકાર) માર્ગ બનાવે છે."
        ),
        developerName = "રાજકુમાર બારીઆ",
        developerPhone = "+91 6352840795",
        developerEmail = "rk3171998@gmail.com",
        developerInstagram = "@rajsbaria",
        feedbackPrompt = "તમારો કિંમતી ફીડબેક (Feedback) ચોક્કસ આપો!",
        names = mapOf(
            "sun" to "સૂર્ય", "mercury" to "બુધ", "venus" to "શુક્ર", "earth" to "પૃથ્વી",
            "mars" to "મંગળ", "ceres" to "સેરેસ", "jupiter" to "ગુરુ", "saturn" to "શનિ",
            "uranus" to "યુરેનસ", "neptune" to "નેપ્ચ્યુન", "pluto" to "પ્લુટો", "haumea" to "હૌમિયા",
            "makemake" to "માકેમાકે", "eris" to "એરિસ", "halley" to "હેલીનો ધૂમકેતુ",
            "apophis" to "એપોફિસ (NEO)", "asteroidBelt" to "એસ્ટેરોઇડ બેલ્ટ", "galCenter" to "આકાશગંગા કેન્દ્ર",
            "proximaCentauri" to "પ્રોક્સિમા સેન્ટૌરી", "alphaCentauri" to "આલ્ફા સેન્ટૌરી",
            "barnardsStar" to "બર્નાર્ડ્સ સ્ટાર", "sirius" to "સિરીયસ",
            "centaurus" to "સેન્ટૌરસ", "ursaMajor" to "ઉર્સા મેજર", "orion" to "ઓરિયન",
            "canisMajor" to "કેનિસ મેજર", "scorpius" to "વૃશ્ચિક", "sagittarius" to "ધન"
        ),
        moonNames = mapOf(
            "earth" to listOf("ચંદ્ર"),
            "mars" to listOf("ફોબોસ", "ડીમોસ"),
            "jupiter" to listOf("આઇઓ", "યુરોપા", "ગેનીમીડ", "કેલિસ્ટો"),
            "saturn" to listOf("ટાઇટન", "એન્સેલાડસ", "મિમાસ"),
            "uranus" to listOf("ટાઇટેનિયા", "ઓબેરોન"),
            "neptune" to listOf("ટ્રાઇટન"),
            "pluto" to listOf("શેરોન", "સ્ટિક્સ", "નિક્સ", "કર્બેરોસ", "હાઇડ્રા"),
            "haumea" to listOf("હીઆકા", "નામાકા"),
            "makemake" to listOf("MK2"),
            "eris" to listOf("ડિસ્નોમિયા")
        )
    )

    private val hi = LocalizedStrings(
        title = "कुंडलित सौर मंडल (राज बारिया)",
        play = "चलाएं",
        pause = "रोकें",
        today = "आज",
        reset = "रीसेट",
        aboutApp = "ऐप के बारे में",
        helpBtn = "मदद / गाइड",
        helpTitle = "ऐप का उपयोग कैसे करें",
        searchGoogle = "Google पर पूछें",
        galSliderText = "गैलेक्सी 360°:",
        focusTargetLabel = "कैमरा फोकस:",
        freeCam = "फ्री कैमरा",
        visibility = "मार्ग दृश्यता:",
        toggleAll = "सभी",
        planetLabels = "ग्रह: ",
        moonLabels = "उपग्रह: ",
        starLabels = "नज़दीकी तारे: ",
        constellationLines = "नक्षत्र रेखाएँ: ",
        galaxyView = "गैलेक्सी: ",
        cometOort = "धूमकेतु और ऊर्ट: ",
        asteroidBelt = "क्षुद्रग्रह घेरा: ",
        solarPaths = "सौर कक्षा: ",
        helicalPaths = "कुंडलित मार्ग: ",
        galOrbit = "आकाशगंगा: ",
        helpItems = listOf(
            "सटीक भौतिकी: NASA JPL डेटा द्वारा सटीक ग्रह और उपग्रहों की चाल!",
            "Asteroid Alert: पृथ्वी के पास आने वाले Apophis जैसे एस्टेरॉयड को देखें।",
            "हेलिकल गति: सूर्य के साथ अंतरिक्ष में ग्रहों का सर्पिलाकार संचलन।"
        ),
        developerName = "राजकुमार बारिया",
        developerPhone = "+91 6352840795",
        developerEmail = "rk3171998@gmail.com",
        developerInstagram = "@rajsbaria",
        feedbackPrompt = "अपनी बहुमूल्य प्रतिक्रिया अवश्य दें!",
        names = mapOf(
            "sun" to "सूर्य", "mercury" to "बुध", "venus" to "शुक्र", "earth" to "पृथ्वी",
            "mars" to "मंगल", "ceres" to "सेरेस", "jupiter" to "बृहस्पति", "saturn" to "शनि",
            "uranus" to "अरुण", "neptune" to "वरुण", "pluto" to "प्लूटो", "haumea" to "हउमेया",
            "makemake" to "माकेमाके", "eris" to "एरिस", "halley" to "हैली का धूमकेतु",
            "apophis" to "Apophis (NEO)", "asteroidBelt" to "क्षुद्रग्रह घेरा", "galCenter" to "आकाशगंगा केंद्र",
            "proximaCentauri" to "प्रॉक्सिमा सेंटॉरी", "alphaCentauri" to "अल्फा सेंटॉरी",
            "barnardsStar" to "बर्नार्ड्स स्टार", "sirius" to "सीरियस",
            "centaurus" to "सेंटॉरस", "ursaMajor" to "उर्सा मेजर", "orion" to "ओरियन",
            "canisMajor" to "कैनिस मेजर", "scorpius" to "वृश्चिक", "sagittarius" to "धनु"
        ),
        moonNames = mapOf(
            "earth" to listOf("चन्द्रमा"),
            "mars" to listOf("फोबोस", "डीमोस"),
            "jupiter" to listOf("आयो", "यूरोपा", "गेनिमीड", "कलिस्टो"),
            "saturn" to listOf("टाइटन", "एन्सेलाडस", "मिमास"),
            "uranus" to listOf("टाइटानिया", "ओबेरॉन"),
            "neptune" to listOf("ट्राइटन"),
            "pluto" to listOf("कॅरन", "स्टिक्स", "निक्स", "कर्बेरोस", "हाइड्रा"),
            "haumea" to listOf("हियाका", "नमाका"),
            "makemake" to listOf("MK2"),
            "eris" to listOf("डिस्नोमिया")
        )
    )

    private val es = LocalizedStrings(
        title = "Sistema Helicoidal de Raj Baria",
        play = "Play",
        pause = "Pausa",
        today = "Hoy",
        reset = "Reset",
        aboutApp = "Acerca de",
        helpBtn = "Ayuda y Guía",
        helpTitle = "Cómo usar",
        searchGoogle = "Buscar en Google",
        galSliderText = "Galaxia 360°:",
        focusTargetLabel = "Foco:",
        freeCam = "Libre",
        visibility = "Rutas:",
        toggleAll = "Todo",
        planetLabels = "Planetas: ",
        moonLabels = "Lunas: ",
        starLabels = "Estrellas: ",
        constellationLines = "Constelaciones: ",
        galaxyView = "Galaxia: ",
        cometOort = "Cometas & Oort: ",
        asteroidBelt = "Cinturón de Asteroides: ",
        solarPaths = "Órbitas: ",
        helicalPaths = "Helicoidales: ",
        galOrbit = "Galáctica: ",
        helpItems = listOf(
            "Física de Kepler: Parámetros orbitales 100% de la NASA JPL J2000.",
            "Alerta de Asteroides: Apophis (99942) y cometa Halley.",
            "Movimiento Helicoidal: Trayectoria tridimensional alrededor de Sagitario A*."
        ),
        developerName = "Rajkumar Baria",
        developerPhone = "+91 6352840795",
        developerEmail = "rk3171998@gmail.com",
        developerInstagram = "@rajsbaria",
        feedbackPrompt = "¡Envíe sus comentarios valiosos!",
        names = mapOf(
            "sun" to "Sol", "mercury" to "Mercurio", "venus" to "Venus", "earth" to "Tierra",
            "mars" to "Marte", "ceres" to "Ceres", "jupiter" to "Júpiter", "saturn" to "Saturno",
            "uranus" to "Urano", "neptune" to "Neptuno", "pluto" to "Plutón", "haumea" to "Haumea",
            "makemake" to "Makemake", "eris" to "Eris", "halley" to "Cometa Halley",
            "apophis" to "Apophis (NEO)", "asteroidBelt" to "Cinturón de Asteroides", "galCenter" to "Sagitario A*",
            "proximaCentauri" to "Próxima Centauri", "alphaCentauri" to "Alfa Centauri",
            "barnardsStar" to "Estrella de Barnard", "sirius" to "Sirio",
            "centaurus" to "Centaurus", "ursaMajor" to "Osa Mayor", "orion" to "Orión",
            "canisMajor" to "Canis Major", "scorpius" to "Escorpio", "sagittarius" to "Sagitario"
        ),
        moonNames = mapOf(
            "earth" to listOf("Luna"),
            "mars" to listOf("Fobos", "Deimos"),
            "jupiter" to listOf("Ío", "Europa", "Ganimedes", "Calisto"),
            "saturn" to listOf("Titán", "Encélado", "Mimas"),
            "uranus" to listOf("Titania", "Oberón"),
            "neptune" to listOf("Tritón"),
            "pluto" to listOf("Caronte", "Estigia", "Nix", "Cerbero", "Hidra"),
            "haumea" to listOf("Hiʻiaka", "Namaka"),
            "makemake" to listOf("MK2"),
            "eris" to listOf("Disnomia")
        )
    )

    private val fr = LocalizedStrings(
        title = "Système Hélicoïdal de Raj Baria",
        play = "Play",
        pause = "Pause",
        today = "Aujourd'hui",
        reset = "Réinitialiser",
        aboutApp = "À propos",
        helpBtn = "Aide & Guide",
        helpTitle = "Comment utiliser",
        searchGoogle = "Rechercher sur Google",
        galSliderText = "Galaxie 360°:",
        focusTargetLabel = "Focus:",
        freeCam = "Libre",
        visibility = "Trajets:",
        toggleAll = "Tout",
        planetLabels = "Planètes: ",
        moonLabels = "Lunes: ",
        starLabels = "Étoiles: ",
        constellationLines = "Constellations: ",
        galaxyView = "Galaxie: ",
        cometOort = "Comètes & Oort: ",
        asteroidBelt = "Ceinture d'Astéroïdes: ",
        solarPaths = "Orbites: ",
        helicalPaths = "Hélicoïdales: ",
        galOrbit = "Galactique: ",
        helpItems = listOf(
            "Physique Képlérienne: Paramètres orbitaux NASA JPL J2000.",
            "Alerte Astéroïde: Apophis (99942) et la comète de Halley.",
            "Trajectoire Hélicoïdale: Le soleil et les planètes en vortex galactique."
        ),
        developerName = "Rajkumar Baria",
        developerPhone = "+91 6352840795",
        developerEmail = "rk3171998@gmail.com",
        developerInstagram = "@rajsbaria",
        feedbackPrompt = "Vos retours sont les bienvenus!",
        names = mapOf(
            "sun" to "Soleil", "mercury" to "Mercure", "venus" to "Vénus", "earth" to "Terre",
            "mars" to "Mars", "ceres" to "Cérès", "jupiter" to "Jupiter", "saturn" to "Saturne",
            "uranus" to "Uranus", "neptune" to "Neptune", "pluto" to "Pluton", "haumea" to "Hauméa",
            "makemake" to "Makémaké", "eris" to "Éris", "halley" to "Comète de Halley",
            "apophis" to "Apophis (NEO)", "asteroidBelt" to "Ceinture d'Astéroïdes", "galCenter" to "Sagittaire A*",
            "proximaCentauri" to "Proxima Centauri", "alphaCentauri" to "Alpha Centauri",
            "barnardsStar" to "Étoile de Barnard", "sirius" to "Sirius",
            "centaurus" to "Centaure", "ursaMajor" to "Grande Ourse", "orion" to "Orion",
            "canisMajor" to "Grand Chien", "scorpius" to "Scorpion", "sagittarius" to "Sagittaire"
        ),
        moonNames = mapOf(
            "earth" to listOf("Lune"),
            "mars" to listOf("Phobos", "Deimos"),
            "jupiter" to listOf("Io", "Europe", "Ganymède", "Callisto"),
            "saturn" to listOf("Titan", "Encelade", "Mimas"),
            "uranus" to listOf("Titania", "Obéron"),
            "neptune" to listOf("Triton"),
            "pluto" to listOf("Charon", "Styx", "Nix", "Kerbéros", "Hydre"),
            "haumea" to listOf("Hiʻiaka", "Namaka"),
            "makemake" to listOf("MK2"),
            "eris" to listOf("Dysnomie")
        )
    )

    private val ja = LocalizedStrings(
        title = "ラージャ・バリアのらせん状太陽系",
        play = "再生",
        pause = "停止",
        today = "今日",
        reset = "リセット",
        aboutApp = "アプリについて",
        helpBtn = "ヘルプとガイド",
        helpTitle = "使い方",
        searchGoogle = "Googleで検索",
        galSliderText = "銀河 360°:",
        focusTargetLabel = "焦点:",
        freeCam = "フリー",
        visibility = "表示:",
        toggleAll = "全切替",
        planetLabels = "惑星: ",
        moonLabels = "衛星: ",
        starLabels = "恒星: ",
        constellationLines = "星座線: ",
        galaxyView = "銀河: ",
        cometOort = "彗星とオールト: ",
        asteroidBelt = "小惑星帯: ",
        solarPaths = "太陽軌道: ",
        helicalPaths = "らせん軌道: ",
        galOrbit = "銀河軌道: ",
        helpItems = listOf(
            "完全なケプラー軌道: NASA JPL J2000に基づく高精度計算。",
            "小惑星アラート: 近地球小惑星アポフィス (99942) とハレー彗星。",
            "らせん運動: いて座A*を中心に太陽系全体が宇宙をらせん状に進みます。"
        ),
        developerName = "Rajkumar Baria (ラージクマル・バリア)",
        developerPhone = "+91 6352840795",
        developerEmail = "rk3171998@gmail.com",
        developerInstagram = "@rajsbaria",
        feedbackPrompt = "貴重なフィードバックをお待ちしております！",
        names = mapOf(
            "sun" to "太陽", "mercury" to "水星", "venus" to "金星", "earth" to "地球",
            "mars" to "火星", "ceres" to "ケレス", "jupiter" to "木星", "saturn" to "土星",
            "uranus" to "天王星", "neptune" to "海王星", "pluto" to "冥王星", "haumea" to "ハウメア",
            "makemake" to "マケマケ", "eris" to "エリス", "halley" to "ハレー彗星",
            "apophis" to "アポフィス (NEO)", "asteroidBelt" to "小惑星帯", "galCenter" to "いて座A*",
            "proximaCentauri" to "プロキシマ・ケンタウリ", "alphaCentauri" to "アルファ・ケンタウリ",
            "barnardsStar" to "バーナード星", "sirius" to "シリウス",
            "centaurus" to "ケンタウルス座", "ursaMajor" to "おおぐま座", "orion" to "オリオン座",
            "canisMajor" to "おおいぬ座", "scorpius" to "さそり座", "sagittarius" to "いて座"
        ),
        moonNames = mapOf(
            "earth" to listOf("月"),
            "mars" to listOf("フォボス", "ダイモス"),
            "jupiter" to listOf("イオ", "エウロパ", "ガニメデ", "カリスト"),
            "saturn" to listOf("タイタン", "エンケラドス", "ミマス"),
            "uranus" to listOf("チタニア", "オベロン"),
            "neptune" to listOf("トリトン"),
            "pluto" to listOf("カロン", "ステュクス", "ニクス", "ケルベロス", "ヒドラ"),
            "haumea" to listOf("ヒイアカ", "ナマカ"),
            "makemake" to listOf("MK2"),
            "eris" to listOf("ディスノミア")
        )
    )

    fun get(lang: AppLanguage): LocalizedStrings = when (lang) {
        AppLanguage.EN -> en
        AppLanguage.GU -> gu
        AppLanguage.HI -> hi
        AppLanguage.ES -> es
        AppLanguage.FR -> fr
        AppLanguage.JA -> ja
    }
}
